### ISSUE TITLE
Difference between ".NET Core,Version=v5.0", ".NET Native,Version=v1.0" and "ASP.NET 5,Version=v1.0" ?

### ISSUE THREAD

**Issue by StefH** [Microsoft/dotnet-apiport#267]
When doing an analyze for my project, I get these **four** frameworks listed in the output.

1. **.NET Core,Version=v5.0 **--> this is "**dnxcore50**" as framework in project.json
2. **.NET Framework,Version=v4.6.1** --> this is "**net46**" as framework in project.json
3. **.NET Native,Version=v1.0** --> this is "**???**" as framework in project.json
4. **ASP.NET 5,Version=v1.0** --> this is "**???**" as framework in project.json

**Comment by conniey** [comment]
Hi,

To answer your question (using the chart from [here](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms)):
1. **.NET Core,Version=v5.0** --> this is "netstandard1.4" as framework in project.json
.NET Core itself is not a targetable platform. If you are trying to write a library that will be supported on future .NET platforms, you should target `netstandard` because any new platforms should implement the .NET Platform Standard.
2. **.NET Framework,Version=v4.6.1** --> this is "net461" as framework in project.json
3. __.NET Native,Version=v1.0__ --> this is "uap10.0" as framework in project.json
4. __ASP.NET 5,Version=v1.0__ --> this is "dotnet5.4" as framework in project.json

Here are a couple of links that will give you more information:
* [Announcement: Switching to new ‘dotnet’ target framework monikers](https://github.com/aspnet/Announcements/issues/98)
* [.NET Platform Standard](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md)

**Comment by fpskcd** [comment]
Does this project support .NET 5 yet?
