### ISSUE TITLE
Targets in JSON are not getting deserialized

### ISSUE THREAD

**Issue by harshdeep21** [Microsoft/dotnet-apiport#280]
Hi There,

I have some 10+ applications which we are trying to migrate. I ran ApiPort exe on all of them and got their JSON file output created. Now, instead of observing JSON file's "BreakingChanges" attributes manually, I created a small program to read all JSON files and apply LNIQ query.

But unfortunately, Newtonsoft JSON library is not able to deserialize "Targets".

`JsonConvert.DeserializeObject<Microsoft.Fx.Portability.ObjectModel.AnalyzeResponse>(File.ReadAllLines(jsonFile))`

I was wondering to know if it's issue from ApiPort library.

Thanks and Regards,
Harshdeep Mehta

**Comment by twsouthwick** [comment]
The issue is probably because Newtonsoft JSON doesn't automatically deserialize Versions. We have a custom converters at https://github.com/Microsoft/dotnet-apiport/tree/master/src/Microsoft.Fx.Portability/Utils/JsonConverters. There are a couple of options:

1) Use the high level helper methods in `DataExtensions` 
2) Pass the settings from `DataExtensions.JsonSettings` into the Json serializer.
3) Use `DataExtensions.JsonSerializer` as your instance of `JsonSerializer`

**Comment by harshdeep21** [comment]
Thanks for the answer. That could help, but those classes are set with "internal" scope. Would it not make sense to make them public?
