### ISSUE TITLE
Analyzing F# assembly?

### ISSUE THREAD

**Issue by Thorium** [Microsoft/dotnet-apiport#304]
Hello,

I made a little F# program and try to analyze the portability of it.
The report gives me a huge list of red crosses even if I use the framework which I build the program with? (IRL the program compiles and works fine.)

```
Assembly   .NET Framework,Version=v4.5.1
MySoftware, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (.NETFramework,Version=v4.5.1)  
73.01%
```

So basically my software is 73% of compatible with the .NET 4.5.1 which is the framework which I used to build it. And it gives zero recommended changes. The problems it reporst are the core F# library functions which are actually working on different platforms just fine:

![Imgur](http://i.imgur.com/kaWePgF.png)

**Comment by Thorium** [comment]
Here is a sample with .NET 4.6.2: http://thorium.kapsi.fi/copy.html

**Comment by conniey** [comment]
Thanks for bringing this to our attention. The reason is because we have not added the F# specific assemblies like FSharp.Core.dll to our profile. I am looking into resolving this.

**Comment by terrajobst** [comment]
It seems we've identified the `Microsoft.FSharp.*` incorrectly as built-in framework APaIs. They should be classified as external API.

I think the reason is that ApiPort [makes the assumption](https://github.com/Microsoft/dotnet-apiport/blob/master/src/Microsoft.Fx.Portability/Analysis/AnalysisEngine.cs#L144) that if the API is listed in the catalog it's a framework API. Since we recently indexed Xamarin and Xamarin includes `FSharp.Core`, the APIs are now flagged as missing from .NET Framwework.

I see a few options:

1. We could whitelist all APIs that are part of the application
2. We could improve the heuristic of framework API detection (namespace, key)
3. We could special case F# Core or include more information in the catalog
   which assemblies are OOB vs. built-in

It's seems (1) is the least fragile option.

**Comment by Thorium** [comment]
My assembly name happens to start with FSharp but not all FSharp apps do. Also FSharp core is not part of my application; the dependency is completely optional as before VS2015 the default installation of Visual Studio had FSharp.core in them.

**Comment by terrajobst** [comment]
@Thorium In order for you app to work on machines that don't have VS (which should be the default for most people) what matter is whether `FSharp.Core` is part of the .NET Framework or not. So if your app assumes the assembly is provided by the machine, then that's only really valid if you essentially pre-req VS. However, from the .NET standpoint that doesn't change the fact that `FSharp.Core` is considered out-of-band, i.e. external to .NET and is expected to be deployed by the app.

**Comment by Thorium** [comment]
Any news on this one?

**Comment by conniey** [comment]
@terrajobst 

> 2. We could improve the heuristic of framework API detection (namespace, key)

We are currently doing this, sort of in [DotNetFrameworkFilter](https://github.com/Microsoft/dotnet-apiport/blob/master/src/Microsoft.Fx.Portability/Analyzer/DotNetFrameworkFilter.cs#L45-L50).  We analyse an API call if it's defined in an assembly that:

1. We see if it has a public key token that is a MSFT public key token, OR
2. Starts with a prefix of "Microsoft.", "System.", or "Mono."

It is trying to analyse his assembly because it has one of the public key tokens from MSFT.  We could fix this by only analysing an assembly if both conditions are met.

**Comment by enricosada** [comment]
If i read correctly you now exclute FSharp.Core warnings from report, and it's ok. But was committed after last public release (october 15 https://github.com/Microsoft/dotnet-apiport/releases/tag/v1.4.0.alpha.00119 ). 
@twsouthwick @conniey Is possibile to have another release of api port? all these errors are really noisy for f# app/lib analyses, and i'd like to tell people to use `apiport` to check F# migrations, but is easier with an already built package
