### ISSUE TITLE
Target Platforms in apiport visual studio addin. (netcoreapp vs asp.netcore)

### ISSUE THREAD

**Issue by niharsanghvi** [Microsoft/dotnet-apiport#316]
I am using visual studio plugin for apiport.  In Tools->Options the target platform list contains netcoreapp 1.0/1.1, netstandard 1.0-1.7 and ASP.NET core 1.0.  
We have a .net based calculation library that we are researching to port to .net core and potentially run it within an asp.net server on linux.  What i am not sure about is should I be running APIPort with target platform set to netcoreapp1.1 or asp.netcore 1.0 ?  Running against asp.net core 1.0 results in a huge list of api's that are incompatible where as against netcore app 1.1 its a much smaller managable list.   What is the difference and which should I target against ?

Also, I havent found any documentation about targetting an application to asp.netcore.  Most blogs/documents talk about asp.net core server targetted to .net core app.  So what is ASP.NET core 1.0 in the target platform list in APIPort really?

**Comment by conniey** [comment]
@terrajobst The set of APIs listed under ASP.NET Core 1.0's API Catalog profile do not include .NET Framework dlls. Is this the correct profile?

**Comment by twsouthwick** [comment]
It contains the .NET Core, as well as ASP.NET Core libraries. You will want to analyze against a .NET Standard, since you are porting a library. The lowest supported standard is the ideal, as it ensures it will be supported across the most platforms. See https://docs.microsoft.com/en-us/dotnet/articles/standard/library for more information
