### ISSUE TITLE
update source code to .net 4.5.2 or even 4.6

### ISSUE THREAD

**Issue by SychevIgor** [Microsoft/dotnet-apiport#317]
https://support.microsoft.com/en-us/gp/framework_faq/en-us?wa=wsignin1.0
As I understand, 4.5 already not supported by Microsoft officially. Maybe it will be better if we will target newer version of .net here...

**Comment by twsouthwick** [comment]
I'm somewhat confused as to what the issue is. Targeting 4.5 (or even 4.0) is still supported. The lowest runtime supported is 4.5.2, but you can still run code targeting 4.5 on higher versions. Is this what you are referring to? If so, please read a recent blog post about it: https://blogs.msdn.microsoft.com/dotnet/2016/05/02/introduction-to-net-framework-compatibility/.

If you are referring to something else, please let me know.

**Comment by twsouthwick** [comment]
I'm going to close. If you feel this is an issue, please clarify your statement and we can continue a discussion.
