### ISSUE TITLE
No "Analyze solution" entry in VS extension

### ISSUE THREAD

**Issue by letmaik** [Microsoft/dotnet-apiport#419]
When I right-click on a solution in Solution Explorer I don't find an entry for running the analysis. The entry is only there when I right-click on a project. I use VS 2015.

**Comment by conniey** [comment]
I believe this is because there may be projects that are not .NET projects (C#/VB/F#/managed C++) in your solution, so it hides the context menu item.

Code: [AnalyzeMenu.cs#L10](https://github.com/Microsoft/dotnet-apiport/blob/2c667d5e8dcdac3f2a3c7e0cc67525a2f58b89b0/src/ApiPort.VisualStudio/AnalyzeMenu.cs#L105)

This isn't desirable behaviour. Probably better to try to analyze all managed projects in your solution and skip the ones that aren't managed.

**Comment by letmaik** [comment]
Right, my current workaround is to use the CLI app.
