### ISSUE TITLE
Unable to contact service error.

### ISSUE THREAD

**Issue by shalinparmar** [Microsoft/dotnet-apiport#528]
After installing the ,NET Portability Anaylzer extension in VS 2017, I see the error:

Unable to contact service. Try again later.

And hence unable to use the utility. Can someone please shed light on what am I missing?

**Comment by conniey** [comment]
Can you provide some repro steps? I know the service was down recently but I installed the VSIX again, tried it out and it appears to be working fine for me.

**Comment by shalinparmar** [comment]
Well, I installed the VS Extension for Portability Analyzer and can't seem to connect to whatever service it is trying to call. When I click "Portability Analyzer Settings" I see "Unable to contact service. Try again Later" error and nothing in Output formats or Target Platforms.

**Comment by conniey** [comment]
Are you behind a proxy? We had fixed this issue #396 for the console application but did not for the VSIX, yet.

@twsouthwick are there any other ways we can debug this issue?

**Comment by shalinparmar** [comment]
Yes I am but it is correct and works with everything else except this one. What service is it trying to access?? Do we have a URL to check that proxy is not the cause?

Thanks!
Shalin

________________________________

**Comment by conniey** [comment]
Hey,
The URI that the VSIX tries to reach is https://portability.dot.net/ (seen here in [ServiceProvider.cs](https://github.com/Microsoft/dotnet-apiport/blob/dev/src/ApiPort.VisualStudio/ServiceProvider.cs#L30)). It makes calls to:
* https://portability.dot.net/api/target to get the target information
* https://portability.dot.net/api/resultFormat to get the supported result formats and
* https://portability.dot.net/api/analyze to analyze the request

The reason it is not working is because we use `HttpClient` to make web requests and currently, do not check whether a system proxy is in place before making those requests. The other extensions you installed probably consider the system proxy.

If you want to work around this, you can download the console application (https://github.com/microsoft/dotnet-apiport/releases) and then use that to analyze your binaries.  This will consider your system proxy and you can configure it as stated in #396

**Comment by twsouthwick** [comment]
I think I've got a fix - I'll get a PR up soon for it
