### ISSUE TITLE
No warnings/errors generated when referencing external DLLs

### ISSUE THREAD

**Issue by CoolDadTx** [Microsoft/dotnet-apiport#620]
As was standard back in the safe/unsafe days of .NET I have a SafeNativeMethods class that P/Invokes to Windows for some missing functionality. There were no warnings/errors reported about this. My assembly was listed as 100% compatible with .NET Core yet these calls would fail on non-Windows.  The only reason I notice this is because I was looking through the files in the project.

```
[SuppressUnmanagedCodeSecurity]
internal static class SafeNativeMethods
{
   [DllImport("shlwapi.dll", CharSet = CharSet.Unicode, ExactSpelling = true, SetLastError = true)]
   public static extern int PathCommonPrefixW ( string pszFile1, string pszFile2, System.Text.StringBuilder pszPath );
}
```
And then later
```
public static class PathExtensions
{
   public static string GetCommonPath ( string path1, string path2 )
   {
      if (String.IsNullOrEmpty(path1) || String.IsNullOrEmpty(path2))
          return "";

      var commonPath = new StringBuilder(MaximumPath);
      if (SafeNativeMethods.PathCommonPrefixW(path1, path2, commonPath) == 0)
         return "";

      return commonPath.ToString();
   }
}
```

**Comment by conniey** [comment]
Hey,

Thanks for bringing up this question! There are different angles we have to look at when understanding the "compatibility" of an application. One component is API compatibility and the other is runtime compatibility.

This tool tries to understand API compatibility between different .NET platforms.  The code will compile on .NET Core because [DllImportAttribute](https://apisof.net/catalog/System.Runtime.InteropServices.DllImportAttribute) is part of the .NET Core API surface area.  And you can run it on .NET Core on Windows. However, on *-nix platforms, it will fail.

Unfortunately, the problem you brought up is out of scope for this tool because we do static analysis on .NET APIs and do not examine potential runtime issues.

I hope this helps,
Connie

**Comment by CoolDadTx** [comment]
I agree that it isn't really an error but this is a hidden failure waiting to happen. The purpose of the tool is to help identify potential issues. I would think that any use of DllImport should trigger a warning or something to review the logic. Otherwise we're back to grepping our code because a DllImport isn't going to work on other platforms without modifications. I'd like to see these "potential problems" be identified as well so I can review them on a case by case basis.

**Comment by chlowell** [comment]
The purpose of this tool is to help identify potential managed API compatibility issues, to help answer the question "would this compile for `some .NET target`" not "would this run on `some OS`".

We recognize `DllImport` can be a landmine and have discussed flagging it in some way in the past. However, it's not always dangerous. A .NET Framework app ported to .NET Core can run on Windows and invoke the same native APIs. It can use a managed API to determine its host OS and invoke native APIs conditionally. ApiPort therefore can't determine whether a P/invoke would fail, or whether it would be used at all. The best it could do is report instances of `DllImportAttribute`, which we think would add more noise than value.
