### ISSUE TITLE
NetStandard 2.0 - Net Framework 4.7 - Incompatibility of DisplayAttribute not reported

### ISSUE THREAD

**Issue by Verarind** [Microsoft/dotnet-apiport#689]
The DisplayAttribute in System.ComponentModel.Annotations (Standard2.0, AssemblyVersion 4.5.0) and System.ComponentModel.DataAnnotations (.Net Framework 4.7) has different AttributeUsage Fields.
While the Standard-Version of the DisplayAttribute allows the usage of the attribute on classes, the .Net Framework-Version of the DisplayAttribute doesn´t allow usage on classes. So the .Net Framework 4.7  strictly speaking does NOT implement Standard2.0. This incompatibility is not reported by Apiport. Maybe there is a possibility to implement a check against the match of Attributes.

Greetings

**Comment by chlowell** [comment]
Thanks for opening this issue. You may be interested in dotnet/corefx#8123, which led to `AttributeTargets.Class` being added to the .NET Core implementation, and has a recent comment asking whether it will be added to the .NET Framework implementation as well.

Although `DisplayAttribute` is provided in a package supporting .NET Standard 2.0, the type isn't part of the 2.0 spec. You can browse that spec with the [.NET API Browser](https://docs.microsoft.com/en-us/dotnet/api/?view=netstandard-2.0), or view it in its entirety at [dotnet/standard](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0_ref.md?raw=true).

As for ApiPort, it can't make this kind of distinction because its source data is essentially equivalent to the raw spec. It compares APIs by their qualified names and has no knowledge of metadata like applied attributes.
