### ISSUE TITLE
An unexpected error was encountered while parsing the metadata for the PE file located at .\References\a-third-party.dll

### ISSUE THREAD

**Issue by MayankSri** [microsoft/dotnet-apiport#956]
Ran the tool on my .Net 4.8 solution and got the error:
This Third party DLL is commercially licensed and referenced through Nuget.

`PS C:\SolutionFolder> apiport analyze -f .`
`Microsoft (R) API Portability Analyzer v2.8.14+6dbb909fac`
`Copyright (C) Microsoft Corporation. All rights reserved.`

`This tool analyzes .NET assemblies to determine possible problems moving between .NET platforms (such as`
`Windows Store, desktop, Mono, .NET Core, etc) as well as between .NET Framework versions (ie 4.x->4.y).`

`To learn more about how this tool works, including the data we are collecting, visit https://aka.ms/dotnet-portabilityanalyzer.`

`For the full privacy statement, please visit https://privacy.microsoft.com/en-us/privacystatement`

`Detecting assembly references                     [Failed]`

`An unexpected error was encountered while parsing the metadata for the PE file located at .\References\[third.party].dll.` 

Version of apiport used is: 2.8.14, ran via CLI.
Any suggestions will be greatly appreciated.

**Comment by Lxiamail** [comment]
@MayankSri thanks for reporting the issue. The problem is as indicated in the error message. To work around the problem, I would suggest you to remove the third party dlls from your folder where you ran apiport to analyze. This is not only to work around the problem, but general best practice. Since the third party dll is commercially licensed and referenced through Nuget, instead of analyzin it's portability, you want to goto NuGet.Org to find out of it has newer version support .NET version that you want to target.  Let me know you have further question.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
