### ISSUE TITLE
What could be the reason for getting the message "No files were found to analyze." when using apiport console app

### ISSUE THREAD

**Issue by amita-git01** [microsoft/dotnet-apiport#986]

**Comment by amita-git01** [comment]
apiport is giving the message "No files were found to analyze"  in spite of the fact that the folder that we specified contains .dll files.

**Comment by Lxiamail** [comment]
@amita-git01 can you share the command that you used?

**Comment by amita-git01** [comment]
Hi,
PFA the screenshot.

Thanks,
Amita
________________________________

**Comment by Lxiamail** [comment]
I didn't see any screen shot. Did I miss anything obvious?

**Comment by amita-git01** [comment]
Yes, It is added as an attachment .

the command used is,

ApiPort.exe analyze -f C:\git\Application

Also, can we know what is the meaning of Skipped Assemblies, that we get in the report along with Unresolved Assemblies


Thanks,
Amita

________________________________

**Comment by amita-git01** [comment]
Hi,
Any update on the below issue.

Thanks,
Amita

________________________________

**Comment by NGloreous** [comment]
I also just hit this issue and for me it turned out to be due to the IsFrameworkAssembly in ReflectionMetadataDependencyInfo.cs. I was trying to analyze some Azure blob libraries to see if I could still use them with .NET Core. After I hacked up the apiport tool I found that yes they are 100% compatible. This seems like a limitation of the tool that you can't analyze some DLLs produced by Microsoft. Could a switch be added to allow such a thing?

**Comment by Lxiamail** [comment]
> Also, can we know what is the meaning of Skipped Assemblies, that we get in the report along with Unresolved Assemblies

Skipped Assemblies mean the assemblies produced by Microsoft. This functionality was added to reduce the noise of the portability report because it is not helpful info but noise to analyze the assemblies that you don't own, like Microsoft assemblies. Instead, for binaries (Microsoft or other third party boinaries) that you don't own, you should look up if there is newer version supports the .NET that you want to move to.

**Comment by NGloreous** [comment]
@Lxiamail in our case we often have no other option than to use the net45 DLLs (e.g. WebAPI, OData, many others). This is an acceptable solution because these DLLs are 100% compatible but the only way to find that out is to hack up the API port tool to allow us to analyze them. Adding an option to allow this would be helpful.

**Comment by andreyn-msft** [comment]
I find this limitation also very irritating

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
